spectre:
  args:
    - "-64"
    - "+interactive"
    - "-format nutbin"
    - "+lqtimeout 900"
    - "-maxw 5"
    - "-maxn 5"
    - "+escchars"
    - "+aps"
    - "+logstatus"
  executable: "/software/CAD/cadence/SPECTRE/1810077/tools/bin/spectre"
  init_script_path: "$HOME/virtuoso_env"
  command_prefix: "tcsh -c 'source $HOME/virtuoso_env && "
  command_postfix: "'"